apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-configmap
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen {{ .Values.deployment.containerPort }};
            location / {
                auth_basic "Restricted Content";
                auth_basic_user_file /etc/secret-volume/.htpasswd;
                root /usr/share/nginx/html;
                index index.html index.htm;
            }
            location {{ .Values.deployment.probes.liveness.path }} { 
                return 200;
            }
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <style>
        body {
          background-color: #1e1e1e;
          color: #d64a4a;
          font-family: Consolas, monospace;
        }
    </style>
    <head>
        <title>Welcome to Nginx!</title>
    </head>
    <body>
        <h1>Success! Nginx is working with Basic Authentication.</h1>
    </body>
    </html>
