apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-app.fullname" . }}-deployment
  labels:
    {{- include "nginx-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }} #Replica count must be configurable.
  selector:
    matchLabels:
      {{- include "nginx-app.selector" . | nindent 6 }}
  template: 
    metadata:
      labels:
        {{- include "nginx-app.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.probes.liveness.path }}
            port: {{ .Values.deployment.probes.liveness.port }}
          initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.probes.readiness.path }}
            port: {{ .Values.deployment.probes.readiness.port }}
          initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.probes.readiness.periodSeconds }}
        startupProbe:
          httpGet:
            path: {{ .Values.deployment.probes.startup.path }}
            port: {{ .Values.deployment.probes.startup.port }}
          failureThreshold: {{ .Values.deployment.probes.startup.failureThreshold }}
          periodSeconds: {{ .Values.deployment.probes.startup.periodSeconds }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-secret
          mountPath: /etc/secret-volume
          readOnly: true
        - name: nginx-pvc
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: nginx-config # Mount ConfigMap and Secret as volumes.
        configMap:
          name: {{include "nginx-app.fullname" . }}-configmap
          optional: false
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: index.html
            path: index.html
      - name: nginx-secret # Mount ConfigMap and Secret as volumes.
        secret:
          secretName: {{include "nginx-app.fullname" . }}-secret
          optional: false
          items:
          - key: USERNAME
            path: USERNAME
          - key: PASSWORD
            path: PASSWORD
          - key: .htpasswd
            path: .htpasswd
      - name: nginx-pvc
        persistentVolumeClaim:
          claimName: {{include "nginx-app.fullname" . }}-pvc
