environment: dev
  
service:
  type: LoadBalancer
  port: 80
  targetPort: 80
  nodePort: 30080

deployment:
  replicas: 1
  name: nginx
  image: nginx:1.14.2
  containerPort: 80
  resources:
    requests:
      cpu: "50m"
      memory: "100Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
  probes:
    liveness:
      path: /healthz
      port: 80
      initialDelaySeconds: 3
      periodSeconds: 10
    readiness:
      path: /healthz
      port: 80
      initialDelaySeconds: 15
      periodSeconds: 5
    startup:
      path: /healthz
      port: 80
      failureThreshold: 30
      periodSeconds: 10

secret:
  username: admin
  password: admin123
  htpasswd: "admin:$apr1$P.w1basQ$QuO5LDGJtfaqGhu7iSnJf1"

persistentVolume:
  storageClassName: nginx-storage
  size: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data
  reclaimPolicy: Delete

hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  metrics:
    type: Resource
    resource:
      name: cpu
      targetType: Utilization
